name: oshama
description: "Milky Mock Server for Application Side Development."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter:
    sdk: flutter

dev_dependencies:
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  build_runner: ^2.10.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
